backend:
  name: github
  repo: leoxmrsh007/jiujing-academy-website
  branch: main
  auth_type: pkce
  app_id: Ov23liW78Dqr2GogKVSY

media_folder: uploads
public_folder: /uploads
locale: zh_Hans

collections:
  - name: news
    label: "\U0001F4F0 书院动态"
    label_singular: 文章
    folder: _news
    create: true
    format: frontmatter
    extension: md
    slug: "{{year}}-{{month}}-{{slug}}"
    summary: "{{title}} - {{date}}"
    sortable_fields:
      - date
      - title
    fields:
      - label: 标题
        name: title
        widget: string
      - label: 日期
        name: date
        widget: string
      - label: 分类
        name: cat
        widget: select
        options:
          - { label: 会讲, value: seminar }
          - { label: 讲座, value: lecture }
          - { label: 游学, value: journey }
          - { label: 札记, value: note }
          - { label: 学员, value: student }
      - label: 正文
        name: body
        widget: markdown

  - name: writings
    label: "\U0001F4AC 学员感悟"
    label_singular: 感悟
    folder: _writings
    create: true
    format: frontmatter
    extension: md
    slug: "{{slug}}"
    summary: "{{author}} - {{date}}"
    fields:
      - label: 姓名
        name: author
        widget: string
      - label: 日期
        name: date
        widget: string
      - label: 正文
        name: body
        widget: markdown
